-- $ psql -U postgres -c "CREATE DATABASE test1"

-- $ psql -U postgres -d "test1" -f script1.sql
-- CREATE DOMAIN
-- CREATE TABLE
-- CREATE TABLE
-- CREATE TABLE
-- CREATE INDEX
-- CREATE INDEX
-- CREATE INDEX
--  schemaname |           tablename           | tableowner | tablespace | hasindexes | hasrules | hastriggers | rowsecurity 
-- ------------+-------------------------------+------------+------------+------------+----------+-------------+-------------
--  public     | ДОМЕННЫЕ ИМЕНА                | postgres   |            | t          | f        | t           | f
--  public     | ПРАВА ПОЛЬЗОВАТЕЛЕЙ НА ДОМЕНЫ | postgres   |            | t          | f        | t           | f
--  public     | ПОЛЬЗОВАТЕЛИ                  | postgres   |            | t          | f        | t           | f
-- (3 rows)

-- $ psql -U postgres -c "DROP DATABASE test1"

create domain NCLOB  as text

;

CREATE TABLE "ПОЛЬЗОВАТЕЛИ" (
	"КЛЮЧ" INT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "НОМЕР ЗАПИСИ О ПОЛЬЗОВАТЕЛЕ" PRIMARY KEY,
	"АДРЕС ЭЛЕКТРОННОЙ ПОЧТЫ" NCLOB,
	"СЕКРЕТ" NCLOB,
	"ПРИЗНАКИ ПАРАНОЙИ" BOOLEAN
)

;

CREATE TABLE "ДОМЕННЫЕ ИМЕНА" (
	"КЛЮЧ" INT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "НОМЕР ЗАПИСИ О ДОМЕНЕ" PRIMARY KEY,
	"ИМЯ ДОМЕНА" NCLOB,
	"ТРЕБУЕТСЯ СЕРТИФИКАТ" BOOLEAN
)

;

CREATE TABLE "ПРАВА ПОЛЬЗОВАТЕЛЕЙ НА ДОМЕНЫ" (
	"КЛЮЧ" INT GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "НОМЕР ЗАПИСИ О ПРАВЕ" PRIMARY KEY,
	"ДОМЕН" INT REFERENCES "ДОМЕННЫЕ ИМЕНА",
	"ПОЛЬЗОВАТЕЛЬ" INT REFERENCES "ПОЛЬЗОВАТЕЛИ",
	"МОЖЕТ РЕДАКТИРОВАТЬ" BOOLEAN
)

;

CREATE INDEX "ППД" ON "ПРАВА ПОЛЬЗОВАТЕЛЕЙ НА ДОМЕНЫ" ("ДОМЕН")

;

CREATE INDEX "ППП" ON "ПРАВА ПОЛЬЗОВАТЕЛЕЙ НА ДОМЕНЫ" ("ПОЛЬЗОВАТЕЛЬ")

;

CREATE UNIQUE INDEX "ПППД" ON "ПРАВА ПОЛЬЗОВАТЕЛЕЙ НА ДОМЕНЫ" ("ДОМЕН", "ПОЛЬЗОВАТЕЛЬ")

;

SELECT * FROM pg_catalog.pg_tables WHERE schemaname != 'pg_catalog' AND  schemaname != 'information_schema'

;

-- SELECT * FROM pg_catalog.pg_type WHERE typname = 'nclob' 
-- ;
